// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dopqxoyxdixlpunavgyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvcHF4b3l4ZGl4bHB1bmF2Z3loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODI3OTEsImV4cCI6MjA2MTY1ODc5MX0.ASWeH9xkwgTZdnx3IWCpfrRHE1B2BBzm4FMkojom91o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);